name: LoafMenus
version: ${project.version}
main: us.figt.loafmenus.example.ExampleMenuPlugin
authors: [FigT]
description: Simplistic, yet powerful GUI API for Spigot.
commands:
  examplemenu:
    usage: /<command>